name: self-hosted runner

on:
  schedule:    
    - cron:  '*/5 * * * *'

jobs:
  pulseCheck:
    runs-on: MATLAB
    steps:
    - name: Instrument MATLAB in bacth mode
      run: matlab -batch 'disp("Hello from self-hosted runner")'
